services:

  application:
    container_name: application
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
    image: application
    volumes:
      - ./:/app/
    networks:
      - net

  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    volumes:
      - index_data:/chroma/.chroma/index
    ports:
      - 8000:8000 # host:container
    networks:
      - net

volumes:
  index_data:
    driver: local
  backups:
    driver: local

networks:
  net:
    driver: bridge