services: 

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - .env
    networks:
      - db_common_default
    volumes:
      - redis_data:/data
      - ./logs/redis:/app/logs/redis  
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data: 

networks:
  db_common_default: 
    driver: bridge
